-- AMCO live tracker setup
create extension if not exists pgcrypto;

create table if not exists public.tracker_rows (
  id bigint generated by default as identity primary key,
  tracker_id text not null,
  kenn text not null,
  model text,
  gru text,
  colour text,
  notes text,
  load_no integer,
  load_pos integer,
  bumper_picking boolean not null default false,
  bumper_picked boolean not null default false,
  cage_picking boolean not null default false,
  cage_picked boolean not null default false,
  checked boolean not null default false,
  complete boolean not null default false,
  despatched boolean not null default false,
  shortage boolean not null default false,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists tracker_rows_tracker_kenn_idx
on public.tracker_rows (tracker_id, kenn);

create index if not exists tracker_rows_tracker_load_idx
on public.tracker_rows (tracker_id, load_no, load_pos);

create or replace function public.set_tracker_rows_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_tracker_rows_updated_at on public.tracker_rows;
create trigger trg_tracker_rows_updated_at
before update on public.tracker_rows
for each row
execute function public.set_tracker_rows_updated_at();

alter table public.tracker_rows enable row level security;

drop policy if exists "tracker_rows_select_all" on public.tracker_rows;
create policy "tracker_rows_select_all"
on public.tracker_rows
for select
to anon, authenticated
using (true);

drop policy if exists "tracker_rows_insert_all" on public.tracker_rows;
create policy "tracker_rows_insert_all"
on public.tracker_rows
for insert
to anon, authenticated
with check (true);

drop policy if exists "tracker_rows_update_all" on public.tracker_rows;
create policy "tracker_rows_update_all"
on public.tracker_rows
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "tracker_rows_delete_all" on public.tracker_rows;
create policy "tracker_rows_delete_all"
on public.tracker_rows
for delete
to anon, authenticated
using (true);

alter publication supabase_realtime add table public.tracker_rows;
